export default {
  'if-then': [
    {
      id: 'XXXXXXX.XXXXXX',
      type: 'mqtt in',
      z: 'XXXXXXX.XXXXXX',
      name: '',
      topic: '',
      qos: '2',
      datatype: 'json',
      broker: 'XXXXXXX.XXXXXX',
      x: 100,
      y: 100,
      wires: [['XXXXXXX.XXXXXX']],
    },
    {
      id: 'XXXXXXX.XXXXXX',
      type: 'switch',
      z: 'XXXXXXX.XXXXXX',
      name: '',
      property: 'payload',
      propertyType: 'msg',
      rules: [],
      checkall: 'true',
      repair: false,
      outputs: 1,
      x: 300,
      y: 150,
      wires: [['XXXXXXX.XXXXXX']],
    },
    {
      id: 'XXXXXXX.XXXXXX',
      type: 'template',
      z: 'XXXXXXX.XXXXXX',
      name: '',
      field: 'payload',
      fieldType: 'msg',
      format: 'handlebars',
      syntax: 'mustache',
      template: 'XXXXXXXXXXXXX',
      output: 'str',
      x: 500,
      y: 200,
      wires: [['XXXXXXX.XXXXXX']],
    },
    {
      id: 'XXXXXXX.XXXXXX',
      type: 'mqtt out',
      z: 'XXXXXXX.XXXXXX',
      name: '',
      topic: '',
      qos: '2',
      retain: 'false',
      x: 700,
      y: 250,
      wires: [],
    },
    {
      id: 'XXXXXXX.XXXXXX',
      type: 'comment',
      z: 'XXXXXXX.XXXXXX',
      name: "Don't edit",
      info: '',
      x: 60,
      y: 20,
      wires: [],
    },
  ],
};
